[package]
name = "mcap_test"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
cu29 = { workspace = true }
libc = "0.2"
mcap = "0.13"
bincode = { workspace = true }
